TYIT/TYIT/urls.py
from django.contrib import admin
from django.urls import path
from employee import views  



urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy), 
    
]

TYIT/urls.py
from django.contrib import admin
from django.urls import path
from employee import views  



urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy), 
    
]

TYIT/employee/models.py
from django.db import models
 
class Employee(models.Model):  
    eid = models.CharField(max_length=20)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15)  
    
    class Meta:  
     db_table = "employee"  

employee/models.py
from django.db import models
 
class Employee(models.Model):  
    eid = models.CharField(max_length=20)  
    ename = models.CharField(max_length=100)  
    eemail = models.EmailField()  
    econtact = models.CharField(max_length=15)  
    
    class Meta:  
     db_table = "employee"  

TYIT/employee/forms.py
from django import forms  
from employee.models import Employee  
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"  

employee/forms.py
from django import forms  
from employee.models import Employee  
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"  

TYIT/employee/views.py
from django.shortcuts import render, redirect 
from employee.forms import EmployeeForm  
from employee.models import Employee  
# Create your views here.  
def emp(request):  
    if request.method == "POST":  
        form = EmployeeForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = EmployeeForm()  
    return render(request,'index.html',{'form':form}) 

def show(request):  
    employees = Employee.objects.all()  
    return render(request,"show.html",{'employees':employees})  

def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'edit.html', {'employee':employee})  

def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'employee': employee})  

def destroy(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/show")  

employee/views.py
from django.shortcuts import render, redirect 
from employee.forms import EmployeeForm  
from employee.models import Employee  
# Create your views here.  
def emp(request):  
    if request.method == "POST":  
        form = EmployeeForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = EmployeeForm()  
    return render(request,'index.html',{'form':form}) 

def show(request):  
    employees = Employee.objects.all()  
    return render(request,"show.html",{'employees':employees})  

def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'edit.html', {'employee':employee})  

def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'employee': employee})  

def destroy(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/show")  

TYIT/templates/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Index</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<style>
  .container1 {
    align-items: center;
        width: 50%;
        margin-top: 8%;
        margin-left: 25%;
        margin-right: 10%;
        border-color: black;
        background-size: 100%;
        background-color: rgb(218, 236, 190);
        color: rgb(43, 40, 40);
    }

  
</style>



<div class="container">
<body>
  <div class="container1" align="center">
    <form method="POST" class="post-form" action="/update/{{employee.id}}">
      {% csrf_token %}
      <div class="container">
        <br>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h2>Update Details</h2>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Id:</label>
          <div class="col-sm-4">
            <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}" />
          </div><br>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Name:</label>
          <div class="col-sm-4">
            <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />
          </div>
        </div><br>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Email:</label>
          <div class="col-sm-4">
            <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />
          </div>
        </div><br>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Contact:</label>
          <div class="col-sm-4">
            <input type="text" name="econtact" id="id_econtact" required maxlength="15"
              value="{{ employee.econtact }}" />
          </div>
        </div><br>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-success">Update</button>
          </div>
        </div>
      </div>
    </form>
    <br>
    <br>
    <br>
  </div>
</body>
</div>

</html>

TYIT/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Index</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<style>

.container{
  background-color: rgb(235, 130, 31);
}



  .container1{
      background-color: aqua;
      margin-top: 8%;
      margin-left: 30%;
      margin-right: 30%;
  }
</style>


<div class="container">
  <br><br>
<body>
  <div class="container1">
  <form method="POST" class="post-form" action="/emp">
    {% csrf_token %}
    <div class="container1" align="center">
      <br>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h2>Enter Details</h2>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Id:</label>
        <div class="col-sm-4">
          {{ form.eid }}
        </div>
      </div><br>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Name:</label>
        <div class="col-sm-4">
          {{ form.ename }}
        </div>
      </div><br>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
        <div class="col-sm-4">
          {{ form.eemail }}
        </div>
      </div><br>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Contact:</label>
        <div class="col-sm-4">
          {{ form.econtact }}
        </div>
      </div><br>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </div>
    <br><br><br>
  </form>
</div>
<br><br><br><br><br><br><br><br>
</body>
</div>

</html>

TYIT/templates/show.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Employee Records</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>


<style>
    .container0 {
       background-color: rgb(235, 130, 31);
       background-size: auto;
       
        
        
    }

    .container1 {
        align-items: center;
        width: 45%;
        margin-top: 5%;
        margin-left: 30%;
        margin-right: 20%;
        border-color: black;
        background-size: 100%;
        background-color: aqua;;
        color: rgb(43, 40, 40);
    }
    
</style>


<div class="container0">
    <br>
    <br>
    <br>
    
<body>
    
    <div class="container1">
        <table class="tadle">
            <thead class="thead-dark">
                <tr>
                    <th><h3><center>Employee ID</center></h3></th>
                    <th><h3><center>Employee Name</center></h3></th>
                    <th><h3><center>Employee Email</center></h3></th>
                    <th><h3><center>Employee Contact</center></h3></th>
                    <th><h3><center>Actions</center></h3></th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td><center>{{ employee.eid }}</center></td>
                    <td><center>{{ employee.ename }}</center></td>
                    <td><center>{{ employee.eemail }}</center></td>
                    <td><center>{{ employee.econtact }}</center></td>
                    <td>
                        
                        <button type="button" class="btn btn-primary"><a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil"><h4><center>Edit</center></h4></span></a></button>
                        <button type="button" class="btn btn-danger" ><a href="/delete/{{ employee.id }}"><h4><center>Delete</center></h4></a></button>
                   
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    
    <br>
    <br>

    <center><button type="button" class="btn btn-success" color="green"><a href="/emp" class="btn btn-primary"><h3><center>Add New Record</center></h3></a></button></center>

    <br><br>
</div>
</body>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>



</html>

templates/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Index</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<style>
  .container1 {
    align-items: center;
        width: 50%;
        margin-top: 8%;
        margin-left: 25%;
        margin-right: 10%;
        border-color: black;
        background-size: 100%;
        background-color: rgb(218, 236, 190);
        color: rgb(43, 40, 40);
    }

  
</style>



<div class="container">
<body>
  <div class="container1" align="center">
    <form method="POST" class="post-form" action="/update/{{employee.id}}">
      {% csrf_token %}
      <div class="container">
        <br>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h2>Update Details</h2>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Id:</label>
          <div class="col-sm-4">
            <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}" />
          </div><br>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Name:</label>
          <div class="col-sm-4">
            <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />
          </div>
        </div><br>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Email:</label>
          <div class="col-sm-4">
            <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />
          </div>
        </div><br>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Employee Contact:</label>
          <div class="col-sm-4">
            <input type="text" name="econtact" id="id_econtact" required maxlength="15"
              value="{{ employee.econtact }}" />
          </div>
        </div><br>
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-success">Update</button>
          </div>
        </div>
      </div>
    </form>
    <br>
    <br>
    <br>
  </div>
</body>
</div>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Index</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<style>

.container{
  background-color: rgb(235, 130, 31);
}



  .container1{
      background-color: aqua;
      margin-top: 8%;
      margin-left: 30%;
      margin-right: 30%;
  }
</style>


<div class="container">
  <br><br>
<body>
  <div class="container1">
  <form method="POST" class="post-form" action="/emp">
    {% csrf_token %}
    <div class="container1" align="center">
      <br>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <h2>Enter Details</h2>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Id:</label>
        <div class="col-sm-4">
          {{ form.eid }}
        </div>
      </div><br>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Name:</label>
        <div class="col-sm-4">
          {{ form.ename }}
        </div>
      </div><br>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Email:</label>
        <div class="col-sm-4">
          {{ form.eemail }}
        </div>
      </div><br>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Employee Contact:</label>
        <div class="col-sm-4">
          {{ form.econtact }}
        </div>
      </div><br>
      <div class="form-group row">
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </div>
    </div>
    <br><br><br>
  </form>
</div>
<br><br><br><br><br><br><br><br>
</body>
</div>

</html>

templates/show.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Employee Records</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>


<style>
    .container0 {
       background-color: rgb(235, 130, 31);
       background-size: auto;
       
        
        
    }

    .container1 {
        align-items: center;
        width: 45%;
        margin-top: 5%;
        margin-left: 30%;
        margin-right: 20%;
        border-color: black;
        background-size: 100%;
        background-color: aqua;;
        color: rgb(43, 40, 40);
    }
    
</style>


<div class="container0">
    <br>
    <br>
    <br>
    
<body>
    
    <div class="container1">
        <table class="tadle">
            <thead class="thead-dark">
                <tr>
                    <th><h3><center>Employee ID</center></h3></th>
                    <th><h3><center>Employee Name</center></h3></th>
                    <th><h3><center>Employee Email</center></h3></th>
                    <th><h3><center>Employee Contact</center></h3></th>
                    <th><h3><center>Actions</center></h3></th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td><center>{{ employee.eid }}</center></td>
                    <td><center>{{ employee.ename }}</center></td>
                    <td><center>{{ employee.eemail }}</center></td>
                    <td><center>{{ employee.econtact }}</center></td>
                    <td>
                        
                        <button type="button" class="btn btn-primary"><a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil"><h4><center>Edit</center></h4></span></a></button>
                        <button type="button" class="btn btn-danger" ><a href="/delete/{{ employee.id }}"><h4><center>Delete</center></h4></a></button>
                   
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    
    <br>
    <br>

    <center><button type="button" class="btn btn-success" color="green"><a href="/emp" class="btn btn-primary"><h3><center>Add New Record</center></h3></a></button></center>

    <br><br>
</div>
</body>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>



</html>